spring:
  cloud:
    gateway:
      routes:
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: product_route
          uri: lb://gulimall-product  # lb负载均衡
          predicates:
            - Path=/api/product/**  # path指定对应路径
          filters: # 重写路径
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: member_route
          uri: lb://gulimall-member  # lb负载均衡
          predicates:
            - Path=/api/member/**  # path指定对应路径
          filters: # 重写路径
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast  # lb负载均衡
          predicates:
            - Path=/api/**  # path指定对应路径
          filters: # 重写路径
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}

