spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: xxxx
      secret-key: xxxxx
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com  ## 地域节点
        bucket: mall00
  application:
    name: gulimall-third-party
server:
  port: 30000
